vich_uploader:
    db_driver: orm

    mappings:
        artistes:
            uri_prefix: /images/artiste
            upload_destination: '%kernel.project_dir%/public/images/artiste'
        movies:
            uri_prefix: /images/movies
            upload_destination: '%kernel.project_dir%/public/images/movies'
